### ISSUE TITLE
Files in target dirs are empty

### ISSUE THREAD

**Issue by marcojez** [Anteru/kyla#1]
Hi there,

I was excited to try this new tool, as I feel it could be useful for managing content within my applications. I'm following the tutorial, but I can't make it work as expected (or I'm doing something wrong). What happens is that after running `kcl install` or `kcl configure`, both of which complete without any error messages, I only get empty files in the deployed directories. That is, all of the expected files are there, but they have zero size.

I'm testing on Crunchbang Linux (Debian based), amd64, within a virtual machine.

**Comment by Anteru** [comment]
That doesn't sound right. Can you upload the installation package somewhere? When you run the build commands, a package will be generated which consists of two files - the repository database and the package itself. Can you please attach them?

Also, what happens when you run `kcl` with verbose output? That's `kcl -l configure` and `kcl -l install`? What output do you get? Empty files should never happen - it should bail out before while decompressing.

**Comment by marcojez** [comment]
Forgot to mention, this happens with the provided sample (GLFW package). I haven't tried to build my own repositories yet. I've attached both the result of running `kcl build`and the result of `kcl install`. Performing the install with log output enabled doesn't show anything that could seem wrong, I just get a bunch of messages like the following:

Debug:   Configure:Received content object 'ca9a1e0d48614d7946f17354b14350003ff2a7d3b10977df512eaad4e5988197'
Debug:   Configure:Stored content object 'ca9a1e0d48614d7946f17354b14350003ff2a7d3b10977df512eaad4e5988197' with id 366
Debug:   Configure:Creating file "docs/html/globals_defs_v.html"
Debug:   Configure:Wrote file "docs/html/globals_defs_v.html"
Debug:   Configure:Received content object 'a69042ab5d9581db570e71efb3284d07cba53cf4df688235fbc2c008a449c091'
Debug:   Configure:Stored content object 'a69042ab5d9581db570e71efb3284d07cba53cf4df688235fbc2c008a449c091' with id 367
Debug:   Configure:Creating file "docs/html/globals_defs_n.html"
Debug:   Configure:Wrote file "docs/html/globals_defs_n.html"
Debug:   Configure:Deleted unused files from repository
Debug:   Configure:Deleted unused file sets from repository
Debug:   Configure:Deleted unused content objects from repository

[deploy-3.1.tar.gz](https://github.com/Anteru/kyla/files/459606/deploy-3.1.tar.gz)
[source-3.1.tar.gz](https://github.com/Anteru/kyla/files/459605/source-3.1.tar.gz)

**Comment by Anteru** [comment]
Thanks, investigating right now :)

**Comment by Anteru** [comment]
I just installed it using: `kcl.exe install source-3.1 target a770816b-d1d7-4e1a-8d9e-014b5041a59c` (in a directory where I extracted your source package into a folder `source-3.1`, so there's a folder called `source-3.1\.ky` with the loose package.) That worked fine - the target folder contains the contents as expected.

**Comment by Anteru** [comment]
Ok, I could reproduce it on Linux - it works on Windows, only the Linux version is affected. Debugging.

**Comment by Anteru** [comment]
Found the issue - just pushed a fix. The `mmap` call was trying to open for read/write always even if the file was opened for read-only. Thanks for the report!

**Comment by marcojez** [comment]
Thank you for fixing it so quickly! I can confirm it works fine now.
