### ISSUE TITLE
GCC needs C++11 to be enabled

### ISSUE THREAD

**Issue by marcojez** [Anteru/kyla#2]
Trying to build kyla with GCC 4.9.2 produces compile error because C++11 is not enabled by default. A simple addition to src/CMakeLists.txt fixes that:

...
`SET(CMAKE_CXX_STANDARD 11)`
...

(I inserted the above statement just below line 4)

**Comment by Anteru** [comment]
You're right - I never tried such an old compiler and hence didn't run into this issue. I'll add it later today.

**Comment by Anteru** [comment]
And done - thanks again!
